./hdl/bootrom_behav.sv
./hdl/konata_behav.sv
./hdl/l2_behav.sv
./hdl/rename_checking_behav.sv
./hdl/commit_log_behav.sv
./cxx/dpi_host.cpp
./cxx/dpi_konata.cpp
./cxx/dpi_perfect_memory.cpp
./cxx/dpi_rename_checking.cpp
./cxx/dpi_commit_log.cpp
./cxx/loadelf.cpp