+incdir+./includes
+incdir+./rtl
+incdir+./rtl/common_cells/include

./rtl/common_cells/include/common_cells/registers.svh
./rtl/common_cells/include/common_cells/assertions.svh
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/cf_math_pkg.sv
./rtl/common_cells/src/lzc.sv
./rtl/common_cells/src/fifo_v3.sv
./rtl/common_cells/src/rr_arb_tree.sv
./rtl/common_cells/src/exp_backoff.sv
./rtl/datapath/rtl/exe_stage/rtl/old_fpu/old_fpnew_pkg.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/cb_filter_pkg.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/ecc_pkg.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/fpnew_pkg.sv
./includes/riscv_pkg.sv
./includes/def_pkg.sv
./includes/drac_pkg.sv
./rtl/register.sv

-F rtl/mmu/filelist.f

./rtl/control_unit/rtl/control_unit.sv
./rtl/datapath/rtl/interface_csr/rtl/csr_interface.sv
./rtl/datapath/rtl/exe_stage/rtl/load_store_queue.sv
./rtl/datapath/rtl/exe_stage/rtl/simd/vshift.sv
./rtl/datapath/rtl/exe_stage/rtl/div_unit.sv
./rtl/datapath/rtl/exe_stage/rtl/pending_mem_req_queue.sv
./rtl/datapath/rtl/exe_stage/rtl/old_fpu/fpu_div_sqrt/old_defs_div_sqrt_mvp.sv
./rtl/datapath/rtl/exe_stage/rtl/old_fpu/fpu_div_sqrt/old_control_mvp.sv
./rtl/datapath/rtl/exe_stage/rtl/old_fpu/fpu_div_sqrt/old_div_sqrt_top_mvp.sv
./rtl/datapath/rtl/exe_stage/rtl/old_fpu/fpu_div_sqrt/old_iteration_div_sqrt_mvp.sv
./rtl/datapath/rtl/exe_stage/rtl/old_fpu/fpu_div_sqrt/old_norm_div_sqrt_mvp.sv
./rtl/datapath/rtl/exe_stage/rtl/old_fpu/fpu_div_sqrt/old_nrbd_nrsc_mvp.sv
./rtl/datapath/rtl/exe_stage/rtl/old_fpu/fpu_div_sqrt/old_preprocess_mvp.sv
./rtl/datapath/rtl/exe_stage/rtl/old_fpu/old_fpnew_cast_multi.sv
./rtl/datapath/rtl/exe_stage/rtl/old_fpu/old_fpnew_classifier.sv
./rtl/datapath/rtl/exe_stage/rtl/old_fpu/old_fpnew_divsqrt_multi.sv
./rtl/datapath/rtl/exe_stage/rtl/old_fpu/old_fpnew_divsqrt_th_32.sv
./rtl/datapath/rtl/exe_stage/rtl/old_fpu/old_fpnew_fma.sv
./rtl/datapath/rtl/exe_stage/rtl/old_fpu/old_fpnew_fma_multi.sv
./rtl/datapath/rtl/exe_stage/rtl/old_fpu/old_fpnew_noncomp.sv
./rtl/datapath/rtl/exe_stage/rtl/old_fpu/old_fpnew_opgroup_block.sv
./rtl/datapath/rtl/exe_stage/rtl/old_fpu/old_fpnew_opgroup_fmt_slice.sv
./rtl/datapath/rtl/exe_stage/rtl/old_fpu/old_fpnew_opgroup_multifmt_slice.sv
./rtl/datapath/rtl/exe_stage/rtl/old_fpu/old_fpnew_rounding.sv
./rtl/datapath/rtl/exe_stage/rtl/old_fpu/old_fpnew_top.sv
./rtl/datapath/rtl/exe_stage/rtl/old_fpu/fpu_drac_wrapper.sv
./rtl/datapath/rtl/exe_stage/rtl/alu/alu.sv
./rtl/datapath/rtl/exe_stage/rtl/alu/alu_add.sv
./rtl/datapath/rtl/exe_stage/rtl/alu/alu_shift.sv
./rtl/datapath/rtl/exe_stage/rtl/alu/alu_logic.sv
./rtl/datapath/rtl/exe_stage/rtl/alu/alu_cmp.sv
./rtl/datapath/rtl/exe_stage/rtl/alu/zero_counter/alu_count_zeros.sv
./rtl/datapath/rtl/exe_stage/rtl/alu/zero_counter/alu_count_zeros_BNE.sv
./rtl/datapath/rtl/exe_stage/rtl/alu/zero_counter/alu_count_zeros_NLC.sv
./rtl/datapath/rtl/exe_stage/rtl/alu/zero_counter/alu_count_zeros_LZC32.sv
./rtl/datapath/rtl/exe_stage/rtl/alu/alu_count_pop.sv
./rtl/datapath/rtl/exe_stage/rtl/exe_stage.sv
./rtl/datapath/rtl/exe_stage/rtl/branch_unit.sv
./rtl/datapath/rtl/exe_stage/rtl/simd/functional_unit.sv
./rtl/datapath/rtl/exe_stage/rtl/simd/vcomp.sv
./rtl/datapath/rtl/exe_stage/rtl/simd/vredtree.sv
./rtl/datapath/rtl/exe_stage/rtl/simd/vmul.sv
./rtl/datapath/rtl/exe_stage/rtl/simd/vpopc.sv
./rtl/datapath/rtl/exe_stage/rtl/simd/viota.sv
./rtl/datapath/rtl/exe_stage/rtl/simd/vfirst.sv
./rtl/datapath/rtl/exe_stage/rtl/simd/vmsb_i_o_f.sv
./rtl/datapath/rtl/exe_stage/rtl/simd/vdiv.sv
./rtl/datapath/rtl/exe_stage/rtl/simd/div_2bits.sv
./rtl/datapath/rtl/exe_stage/rtl/pending_fp_ops_queue.sv
./rtl/datapath/rtl/exe_stage/rtl/score_board_scalar.sv
./rtl/datapath/rtl/exe_stage/rtl/score_board_simd.sv
./rtl/datapath/rtl/exe_stage/rtl/mul_unit.sv
./rtl/datapath/rtl/exe_stage/rtl/mem_unit.sv
./rtl/datapath/rtl/exe_stage/rtl/simd/simd_unit.sv
./rtl/datapath/rtl/exe_stage/rtl/simd/vaddsub.sv
./rtl/datapath/rtl/exe_stage/rtl/simd/vsaaddsub.sv
./rtl/datapath/rtl/exe_stage/rtl/simd/vwaddsub.sv
./rtl/datapath/rtl/exe_stage/rtl/simd/vnclip.sv
./rtl/datapath/rtl/exe_stage/rtl/simd/vsmul.sv
./rtl/datapath/rtl/exe_stage/rtl/div_4bits.sv
./rtl/datapath/rtl/exe_stage/rtl/store_buffer.sv
./rtl/datapath/rtl/exe_stage/rtl/vagu.sv
./rtl/datapath/rtl/if_stage_1/rtl/bimodal_predictor.sv
./rtl/datapath/rtl/if_stage_1/rtl/return_address_stack.sv
./rtl/datapath/rtl/if_stage_1/rtl/branch_predictor.sv
./rtl/datapath/rtl/if_stage_1/rtl/if_stage_1.sv
./rtl/datapath/rtl/datapath.sv
./rtl/datapath/rtl/ir_stage/rtl/free_list.sv
./rtl/datapath/rtl/ir_stage/rtl/instruction_queue.sv
./rtl/datapath/rtl/ir_stage/rtl/rename_table.sv
./rtl/datapath/rtl/if_stage_2/rtl/if_stage_2.sv
./rtl/datapath/rtl/id_stage/rtl/immediate.sv
./rtl/datapath/rtl/id_stage/rtl/decoder.sv
./rtl/datapath/rtl/id_stage/rtl/vset_module.sv
./rtl/datapath/rtl/id_stage/rtl/vset_queue.sv
./rtl/datapath/rtl/rr_stage/rtl/regfile.sv
./rtl/datapath/rtl/wb_stage/rtl/graduation_list.sv

./rtl/csr/rtl/csr_bsc.sv
./rtl/csr/rtl/hpm_counters.sv

./rtl/top_drac.sv

./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/addr_decode.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/binary_to_gray.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/cb_filter.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/cdc_2phase.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/cdc_fifo_2phase.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/cdc_fifo_gray.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/clk_div.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/counter.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/delta_counter.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/deprecated/clock_divider.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/deprecated/clock_divider_counter.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/deprecated/fifo_v1.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/deprecated/fifo_v2.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/deprecated/find_first_one.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/deprecated/generic_LFSR_8bit.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/deprecated/generic_fifo.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/deprecated/generic_fifo_adv.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/deprecated/prioarbiter.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/deprecated/pulp_sync.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/deprecated/pulp_sync_wedge.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/deprecated/rrarbiter.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/ecc_decode.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/ecc_encode.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/edge_detect.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/edge_propagator.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/edge_propagator_rx.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/edge_propagator_tx.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/exp_backoff.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/fall_through_register.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/fifo_v3.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/gray_to_binary.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/id_queue.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/isochronous_spill_register.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/lfsr.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/lfsr_16bit.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/lfsr_8bit.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/lzc.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/max_counter.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/mv_filter.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/onehot_to_bin.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/plru_tree.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/popcount.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/rr_arb_tree.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/rstgen.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/rstgen_bypass.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/serial_deglitch.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/shift_reg.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/spill_register.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/stream_arbiter.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/stream_arbiter_flushable.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/stream_delay.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/stream_demux.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/stream_fifo.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/stream_filter.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/stream_fork.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/stream_fork_dynamic.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/stream_intf.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/stream_join.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/stream_mux.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/stream_omega_net.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/stream_register.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/stream_to_mem.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/stream_xbar.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/sub_per_hash.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/sync.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/sync_wedge.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/common_cells/src/unread.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/fpnew_cast_multi.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/fpnew_classifier.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/fpnew_divsqrt_multi.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/fpnew_divsqrt_th_32.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/fpnew_fma.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/fpnew_fma_multi.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/fpnew_noncomp.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/fpnew_opgroup_block.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/fpnew_opgroup_fmt_slice.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/fpnew_opgroup_multifmt_slice.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/fpnew_rounding.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/fpnew_top.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/fpu_div_sqrt_mvp/hdl/control_mvp.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/fpu_div_sqrt_mvp/hdl/div_sqrt_mvp_wrapper.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/fpu_div_sqrt_mvp/hdl/div_sqrt_top_mvp.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/fpu_div_sqrt_mvp/hdl/iteration_div_sqrt_mvp.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/fpu_div_sqrt_mvp/hdl/norm_div_sqrt_mvp.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/fpu_div_sqrt_mvp/hdl/nrbd_nrsc_mvp.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/src/fpu_div_sqrt_mvp/hdl/preprocess_mvp.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/clk/rtl/gated_clk_cell.v
./rtl/datapath/rtl/exe_stage/rtl/fpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ctrl.v
./rtl/datapath/rtl/exe_stage/rtl/fpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ff1.v
./rtl/datapath/rtl/exe_stage/rtl/fpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_pack_single.v
./rtl/datapath/rtl/exe_stage/rtl/fpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_prepare.v
./rtl/datapath/rtl/exe_stage/rtl/fpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_round_single.v
./rtl/datapath/rtl/exe_stage/rtl/fpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_special.v
./rtl/datapath/rtl/exe_stage/rtl/fpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_srt_single.v
./rtl/datapath/rtl/exe_stage/rtl/fpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_top.v
./rtl/datapath/rtl/exe_stage/rtl/fpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_dp.v
./rtl/datapath/rtl/exe_stage/rtl/fpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_frbus.v
./rtl/datapath/rtl/exe_stage/rtl/fpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_src_type.v
./rtl/datapath/rtl/exe_stage/rtl/simd/vf7_mf.sv
./rtl/datapath/rtl/exe_stage/rtl/simd/vfpu_drac_wrapper.sv
./rtl/datapath/rtl/exe_stage/rtl/simd/pending_vfp_ops_queue.sv
