./rtl/dcache/rtl/src/target/generic/hpdcache_params_pkg.sv
./rtl/dcache/rtl/src/hpdcache_pkg.sv
./rtl/dcache/rtl/include/hpdcache_typedef.svh
./includes/fpuv_pkg.sv
./includes/fpuv_wrapper_pkg.sv
./includes/riscv_pkg.sv
./includes/def_pkg.sv
./includes/drac_pkg.sv
./rtl/mmu/includes/mmu_pkg.sv
./includes/sargantana_icache_pkg.sv
./rtl/interface_icache/rtl/icache_interface.sv
./rtl/control_unit/rtl/control_unit.sv
./rtl/register.sv
./rtl/icache/rtl/sargantana_cleaning_module.sv
./rtl/icache/rtl/sargantana_icache_memory/rtl/sargantana_idata_memory.sv
./rtl/icache/rtl/sargantana_icache_memory/rtl/sargantana_tag_way_memory.sv
./rtl/icache/rtl/sargantana_icache_memory/rtl/sargantana_itag_memory.sv
./rtl/icache/rtl/sargantana_icache_memory/rtl/sargantana_set_ram.sv
./rtl/icache/rtl/sargantana_icache_memory/rtl/sargantana_itag_memory_sram.sv
./rtl/icache/rtl/sargantana_icache_memory/rtl/sargantana_top_memory.sv
./rtl/icache/rtl/sargantana_icache_memory/rtl/sargantana_icache_way.sv
./rtl/icache/rtl/sargantana_icache_tzc.sv
./rtl/icache/rtl/sargantana_icache_lfsr.sv
./rtl/icache/rtl/sargantana_icache_checker.sv
./rtl/icache/rtl/sargantana_icache_ctrl/rtl/sargantana_icache_ctrl.sv
./rtl/icache/rtl/sargantana_icache_tzc_idx.sv
./rtl/icache/rtl/sargantana_icache_ff.sv
./rtl/icache/rtl/sargantana_icache_replace_unit.sv
./rtl/icache/rtl/sargantana_top_icache.sv
./rtl/datapath/rtl/interface_csr/rtl/csr_interface.sv
./rtl/datapath/rtl/exe_stage/rtl/load_store_queue.sv
./rtl/datapath/rtl/exe_stage/rtl/vshift.sv
./rtl/datapath/rtl/exe_stage/rtl/div_unit.sv
./rtl/datapath/rtl/exe_stage/rtl/pending_mem_req_queue.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/fpuv_divsqrt_multi.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/fpuv_rr_arb_tree.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/fpuv_fma.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/fpuv_classifier.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/fpuv_rounding.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/fpuv_fma_multi.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/divsqrt_iter.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/fpuv_opgroup_fmt_slice.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/fpu_drac_wrapper.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/fpuv_noncomp.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/divsqrt_top.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/divsqrt_nrst.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/fpuv_opgroup_multifmt_slice.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/fpuv_cast_multi.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/fpuv_lzc.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/fpuv_opgroup_block.sv
./rtl/datapath/rtl/exe_stage/rtl/fpu/fpuv_top.sv
./rtl/datapath/rtl/exe_stage/rtl/alu.sv 
./rtl/datapath/rtl/exe_stage/rtl/exe_stage.sv 
./rtl/datapath/rtl/exe_stage/rtl/branch_unit.sv 
./rtl/datapath/rtl/exe_stage/rtl/functional_unit_mc.sv
./rtl/datapath/rtl/exe_stage/rtl/functional_unit.sv
./rtl/datapath/rtl/exe_stage/rtl/vcomp.sv
./rtl/datapath/rtl/exe_stage/rtl/vred.sv
./rtl/datapath/rtl/exe_stage/rtl/vmul.sv
./rtl/datapath/rtl/exe_stage/rtl/pending_fp_ops_queue.sv
./rtl/datapath/rtl/exe_stage/rtl/score_board_scalar.sv
./rtl/datapath/rtl/exe_stage/rtl/score_board_simd.sv
./rtl/datapath/rtl/exe_stage/rtl/mul_unit.sv
./rtl/datapath/rtl/exe_stage/rtl/mem_unit.sv
./rtl/datapath/rtl/exe_stage/rtl/simd_unit_mc.sv
./rtl/datapath/rtl/exe_stage/rtl/simd_unit.sv 
./rtl/datapath/rtl/exe_stage/rtl/vaddsub.sv 
./rtl/datapath/rtl/exe_stage/rtl/div_4bits.sv 
./rtl/datapath/rtl/exe_stage/rtl/store_buffer.sv 
./rtl/datapath/rtl/if_stage_1/rtl/bimodal_predictor.sv
./rtl/datapath/rtl/if_stage_1/rtl/return_address_stack.sv
./rtl/datapath/rtl/if_stage_1/rtl/branch_predictor.sv
./rtl/datapath/rtl/if_stage_1/rtl/if_stage_1.sv
./rtl/datapath/rtl/datapath.sv
./rtl/datapath/rtl/ir_stage/rtl/simd_rename_table.sv
./rtl/datapath/rtl/ir_stage/rtl/fp_rename_table.sv
./rtl/datapath/rtl/ir_stage/rtl/simd_free_list.sv
./rtl/datapath/rtl/ir_stage/rtl/fp_free_list.sv
./rtl/datapath/rtl/ir_stage/rtl/free_list.sv
./rtl/datapath/rtl/ir_stage/rtl/instruction_queue.sv
./rtl/datapath/rtl/ir_stage/rtl/rename_table.sv
./rtl/datapath/rtl/if_stage_2/rtl/if_stage_2.sv
./rtl/datapath/rtl/id_stage/rtl/immediate.sv
./rtl/datapath/rtl/id_stage/rtl/decoder.sv
./rtl/datapath/rtl/rr_stage/rtl/regfile.sv
./rtl/datapath/rtl/rr_stage/rtl/vregfile.sv
./rtl/datapath/rtl/rr_stage/rtl/regfile_fp.sv
./rtl/datapath/rtl/wb_stage/rtl/graduation_list.sv
./rtl/interface_dcache/rtl/dcache_interface.sv
./rtl/csr/rtl/csr_bsc.sv
./rtl/mmu/src/rtl/pseudoLRU.sv
./rtl/mmu/src/rtl/ptw_arb.sv
./rtl/mmu/src/rtl/ptw.sv
./rtl/mmu/src/rtl/tlb.sv
./rtl/hpm/rtl/hpm_counters.sv
./rtl/dcache/rtl/src/common/hpdcache_demux.sv
./rtl/dcache/rtl/src/common/hpdcache_fifo_reg.sv
./rtl/dcache/rtl/src/common/hpdcache_fxarb.sv
./rtl/dcache/rtl/src/common/hpdcache_rrarb.sv
./rtl/dcache/rtl/src/common/hpdcache_mux.sv
./rtl/dcache/rtl/src/common/hpdcache_prio_1hot_encoder.sv
./rtl/dcache/rtl/src/common/hpdcache_sram.sv
./rtl/dcache/rtl/src/common/macros/behav/hpdcache_sram_1rw.sv
./rtl/dcache/rtl/src/common/macros/behav/hpdcache_sram_wmask_1rw.sv
./rtl/dcache/rtl/src/common/hpdcache_sram_wmask.sv
./rtl/dcache/rtl/src/common/hpdcache_data_downsize.sv
./rtl/dcache/rtl/src/common/hpdcache_data_upsize.sv
./rtl/dcache/rtl/src/hwpf_stride/hwpf_stride_pkg.sv
./rtl/dcache/rtl/src/hwpf_stride/hwpf_stride.sv
./rtl/dcache/rtl/src/hwpf_stride/hwpf_stride_arb.sv
./rtl/dcache/rtl/src/hwpf_stride/hwpf_stride_snooper.sv
./rtl/dcache/rtl/src/hwpf_stride/hwpf_stride_wrapper.sv
./rtl/dcache/rtl/src/hpdcache.sv
./rtl/dcache/rtl/src/hpdcache_amo.sv
./rtl/dcache/rtl/src/hpdcache_cmo.sv
./rtl/dcache/rtl/src/hpdcache_ctrl.sv
./rtl/dcache/rtl/src/hpdcache_ctrl_pe.sv
./rtl/dcache/rtl/src/hpdcache_memarray.sv
./rtl/dcache/rtl/src/hpdcache_memctrl.sv
./rtl/dcache/rtl/src/hpdcache_miss_handler.sv
./rtl/dcache/rtl/src/hpdcache_mshr.sv
./rtl/dcache/rtl/src/hpdcache_mshr_to_cache_set.sv
./rtl/dcache/rtl/src/hpdcache_plru.sv
./rtl/dcache/rtl/src/hpdcache_rtab.sv
./rtl/dcache/rtl/src/hpdcache_uncached.sv
./rtl/dcache/rtl/src/hpdcache_wbuf.sv
./rtl/dcache/rtl/src/hpdcache_wbuf_wrapper.sv
./rtl/dcache/rtl/src/utils/hpdcache_mem_req_read_arbiter.sv
./rtl/dcache/rtl/src/utils/hpdcache_mem_req_write_arbiter.sv
./rtl/dcache/rtl/src/utils/hpdcache_mem_resp_demux.sv
./rtl/top_drac.sv
