spi_eeprom_req-sim:
	cd tb/tb_spi_eeprom_req/ && make sim
spi_eeprom_req-sim_gui:
	cd tb/tb_spi_eeprom_req/ && make sim-gui

bootrom_ctrl-sim:
	cd tb/tb_bootrom_ctrl && make sim
bootrom_ctrl-sim_gui:
	cd tb/tb_bootrom_ctrl && make sim-gui

clean-all:
	cd tb/tb_spi_eeprom_req && make clean
	cd tb/tb_bootrom_ctrl && make clean
